### ISSUE TITLE
This feature is not available for this version of Python

### ISSUE THREAD

**Issue by mugbya** [lixxu/sanic-jinja2#1]
env:  python3.5.2    sanic 0.3.1

hello

I get error when run this example

>2017-03-02 22:36:38,197: ERROR: Exception occurred while handling uri: "/"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sanic/sanic.py", line 329, in handle_request
    response = await response
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/Users/mugbya/git/mine/sanic-jinja2/example/hello.py", line 34, in index
    return await jinja.render('index.html', request, greetings='Hello, sanic!')
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/Users/mugbya/git/mine/sanic-jinja2/sanic_jinja2/__init__.py", line 54, in render
    return html(await self.render_string(template, request, **context))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/Users/mugbya/git/mine/sanic-jinja2/sanic_jinja2/__init__.py", line 51, in render_string
    return await self.env.get_template(template).render_async(**context)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 1020, in render_async
    raise NotImplementedError('This feature is not available for this '
NotImplementedError: This feature is not available for this version of Python

**Comment by mugbya** [comment]
jinja2 的 jinja2/environment.py 中有如下描述：

    def render_async(self, *args, **kwargs):
        """This works similar to :meth:`render` but returns a coroutine
        that when awaited returns the entire rendered template string.  This
        requires the async feature to be enabled.

        Example usage::

            await template.render_async(knights='that say nih; asynchronously')
        """
        # see asyncsupport for the actual implementation
        raise NotImplementedError('This feature is not available for this '
                                  'version of Python')

so 返回的时候应该去掉了 await ？ 你怎么运行起来的 ？

**Comment by lixxu** [comment]
seems only in 3.6, may be should be disable `async` default

**Comment by lixxu** [comment]
disable async by default, sorry for that.
