### ISSUE TITLE
ModuleNotFoundError: No module named error

### ISSUE THREAD

**Issue by facundopadilla** [lixxu/sanic-jinja2#44]
I am running the example that is in the project repository but it does not work.
Python version: 3.8.5

aiofiles==0.7.0
httptools==0.2.0
Jinja2==3.0.1
MarkupSafe==2.0.1
multidict==5.1.0
sanic==21.3.4
sanic-jinja2==0.10.0
sanic-routing==0.6.2
sanic-session==0.8.0
ujson==4.0.2
uvloop==0.15.2
websockets==8.1

![imagen](https://user-images.githubusercontent.com/64610246/122444550-0bbe2280-cf77-11eb-9f45-69e3bbbd4a0f.png)

```
Traceback (most recent call last):
  File "otra.py", line 9, in <module>
    jinja = SanicJinja2(app, session=session)
  File "/home/facundo/insumos/env_insumos/lib/python3.8/site-packages/sanic_jinja2/__init__.py", line 95, in __init__
    self.init_app(app, loader, pkg_name or app.name, pkg_path)
  File "/home/facundo/insumos/env_insumos/lib/python3.8/site-packages/sanic_jinja2/__init__.py", line 119, in init_app
    loader = PackageLoader(
  File "/home/facundo/insumos/env_insumos/lib/python3.8/site-packages/jinja2/loaders.py", line 285, in __init__
    import_module(package_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'asd'
```

**Comment by ahopkins** [comment]
I think the problem is with the example in the repo, and on the README.

```python
app = Sanic("myapp")
```

And setting your app up like this:

```
.
├── myapp
│   ├── example.png
│   ├── __init__.py
│   └── templates
│       ├── base.html
│       ├── index.html
│       └── __init__.py
└── server.py
```

**Comment by facundopadilla** [comment]
> I think the problem is with the example in the repo, and on the README.
> 
> ```python
> app = Sanic("myapp")
> ```
> 
> And setting your app up like this:
> 
> ```
> .
> ├── myapp
> │   ├── example.png
> │   ├── __init__.py
> │   └── templates
> │       ├── base.html
> │       ├── index.html
> │       └── __init__.py
> └── server.py
> ```

thanks! this works :D
