### ISSUE TITLE
Can't load the template

### ISSUE THREAD

**Issue by zhenzi0322** [lixxu/sanic-jinja2#46]
```python
from sanic import Sanic
from sanic_jinja2 import SanicJinja2

app = Sanic(__name__)
jinja = SanicJinja2(app)
jinja.init_app(app)


@app.route('/')
@jinja.template('index.html')  # decorator method is staticmethod
async def index(request):
    return {'greetings': 'Hello, sanic!'}


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)
```
Output:
```
Traceback (most recent call last):
  File "F:/python/tortoise_demo/demo.py", line 5, in <module>
    jinja = SanicJinja2(app)
  File "D:\python375\Envs\test\lib\site-packages\sanic_jinja2\__init__.py", line 95, in __init__
    self.init_app(app, loader, pkg_name or app.name, pkg_path)
  File "D:\python375\Envs\test\lib\site-packages\sanic_jinja2\__init__.py", line 120, in init_app
    pkg_name or app.name, pkg_path or "templates"
  File "D:\python375\Envs\test\lib\site-packages\jinja2\loaders.py", line 286, in __init__
    spec = importlib.util.find_spec(package_name)
  File "d:\python375\lib\importlib\util.py", line 114, in find_spec
    raise ValueError('{}.__spec__ is None'.format(name))
ValueError: __main__.__spec__ is None
```
version:
```
sanic=21.6.0
sanic-jinja2=0.10.0
```

**Comment by lixxu** [comment]
please check out #43.

**Comment by zhenzi0322** [comment]
> please check out #43.

Still so
[https://imgtu.com/i/W78DQx ](https://imgtu.com/i/W78DQx )

In fact, I was able to do it yesterday, I don't know why it didn't work again today, the code is still the same

**Comment by lixxu** [comment]
very strange, I'm using python3.8. maybe you give it a try.

**Comment by zhenzi0322** [comment]
我已经解决了,谢谢

**Comment by lonngxiang** [comment]
> 我已经解决了,谢谢
麻烦问下怎么解决的吗，一样的问题

**Comment by zhenzi0322** [comment]
> > 我已经解决了,谢谢麻烦问下怎么解决的吗，一样的问题

环境路径的问题

**Comment by lonngxiang** [comment]
> 环境路径的问题

路径吗？我解决的是因为版本，我降级了成功

**Comment by zhenzi0322** [comment]
> > 环境路径的问题
> 
> 路径吗？我解决的是因为版本，我降级了成功

我之前使用的版本是`3.7.5`。但是有的时候我换成其他虚拟环境下执行又没有出现那种错误了。

**Comment by lonngxiang** [comment]
> > > 环境路径的问题
> > 
> > 
> > 路径吗？我解决的是因为版本，我降级了成功
> 
> 我之前使用的版本是`3.7.5`。但是有的时候我换成其他虚拟环境下执行又没有出现那种错误了。

是的，我也遇到过；我是降低jinja2的版本就work了

**Comment by zhenzi0322** [comment]
> 是的，我也遇到过；我是降低jinja2的版本就work了

解决了就行，目前不知道作者有没有修复这个小`bug`。降低版本解决了就行了。

**Comment by lixxu** [comment]
> > 是的，我也遇到过；我是降低jinja2的版本就work了
> 
> 解决了就行，目前不知道作者有没有修复这个小`bug`。降低版本解决了就行了。
> 
> 

这个是新版jinja2带来的变动，我这里貌似修复不了，后续我再研究一下看看。
